//! Convert CLI arguments to YAML configuration.

use std::path::Path;

use crate::cli::Args;
use crate::config::Config;
use crate::operations::pull::{build_config_from_args, build_merged_config};
use anyhow::Result;
use os_shim::System;

/// Convert arguments to YAML configuration.
///
/// # Errors
///
/// Returns an error if:
/// - The configuration file cannot be loaded or parsed
/// - The configuration is invalid
/// - The configuration cannot be serialized to YAML
#[inline]
pub fn generate_yaml_config(args: &Args, system: &dyn System) -> Result<String> {
    // Build the config structure
    let config = if Path::new(&args.config).exists() {
        // Load and merge with CLI overrides
        build_merged_config(args, system)?
    } else if !args.pulls.sources.is_empty() {
        // Build from CLI args only
        build_config_from_args(args)?
    } else {
        return Err(anyhow::anyhow!(
            "No configuration source provided. Specify --config or provide pull arguments."
        ));
    };

    // Validate the config
    config.validate(system)?;

    // Serialize to YAML with clean formatting
    serialize_config(&config)
}

/// Serialize Config to YAML string with proper formatting.
fn serialize_config(config: &Config) -> Result<String> {
    // Use serde_yaml with custom formatting
    let yaml = serde_yaml::to_string(config)
        .map_err(|err| anyhow::anyhow!("Failed to serialize config to YAML: {err}"))?;

    // Post-process for better formatting
    let formatted = format_yaml_output(&yaml);

    Ok(formatted)
}

/// Format YAML output for readability.
fn format_yaml_output(yaml: &str) -> String {
    // Add helpful comment at top
    let mut output = String::from("# Generated by tixgraft --to-config\n");
    output.push_str("# https://github.com/tixena/tixgraft\n\n");

    // Add the YAML content
    output.push_str(yaml);

    // Ensure trailing newline
    if !output.ends_with('\n') {
        output.push('\n');
    }

    output
}

#[cfg(test)]
mod tests;
